linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  gosec:
    excludes:
      - G107 # SSRF protection

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

run:
  timeout: 5m
